spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 500
    #open-in-view: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/querydsl
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: debug
